import type { Metadata } from "next";
import { Montserrat, Cormorant } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Subscribe from "@/components/Subscribe";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font--montserrat",
});

const cormorant = Cormorant({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font--cormorant",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable}  ${cormorant.variable} overflow-x-hidden antialiased`}
      >
        <Header />

        {children}
        <Subscribe />
        <Footer />
      </body>
    </html>
  );
}
